Repository chas-academy/Cobalt-api, pull requests merged in 2018-05, with the labels that each got.

#8 Updates structure adds vote functionality
  package.json
  src/config/config.js
  src/controllers/AuthController.js
  src/controllers/SessionController.js
  src/controllers/UserController.js
  src/db/actions.js
  src/models/Presentation.js
  src/server.js
  src/services/passport.js
  src/socket/onSocketActions.js
  src/socket/socket.js
Labels: review

#10 9 feature/saving presentations
  package.json
  src/controllers/SessionController.js
  src/controllers/UserController.js
  src/db/actions.js
  src/db/actions.test.js
  src/models/Presentation.js
  src/models/User.js
  src/models/Workspace.js
  src/server.js
  src/socket/onSocketActions.js
  src/socket/socket.js
  src/utils/fp.js
Labels: enhancement, review

#20 Feature/control session owner. Closes #19
  src/controllers/SessionController.js
  src/db/actions.js
  src/socket/onSocketActions.js
  src/socket/socket.js
Labels: review

#15 Removes comments sends settings on wizard creation
  src/controllers/SessionController.js
  src/db/actions.js
  src/socket/onSocketActions.js
Labels: review

#21 Hotfix/messages
  src/controllers/AuthController.js
  src/controllers/SessionController.js
  src/controllers/UserController.js
Labels: review

#22 Fix duplicate export identifiers
  src/db/actions.js
Labels: review

#23 Add method to get user data. Closes #13
  src/controllers/UserController.js
  src/db/actions.js
  src/models/User.js
Labels: review

#26 Saves attendees to DB on session end
  src/db/actions.js
  src/models/Presentation.js
  src/socket/onSocketActions.js
Labels: review

#27 Feature/deployment
  .babelrc
  deploy/.env.dev
  deploy/.env.dist
  deploy/.env.prod
  deploy/.env.staging
  deploy/Dockerfile.prod
  deploy/docker-stack-dev.yml
  deploy/docker-stack-production.yml
  deploy/docker-stack-staging.yml
  docker-compose-prod.yml
  package.json
  src/models/User.js
  yarn.lock
Labels: review

#29 28 feature/delete session
  package.json
  src/controllers/SessionController.js
  src/db/actions.js
  src/server.js
Labels: feature, review

#36 Endpoint: Logout
  src/controllers/AuthController.js
Labels: review

#37 Adds basic tests, minor fix to actions
  package.json
  src/db/actions.js
  src/db/actions.test.js
  src/services/passport.js
Labels: review

#41 feature/CRUD members workspace
  src/controllers/WorkspaceController.js
  src/db/actions.js
  src/models/Subscription.js
  src/models/Workspace.js
  src/server.js
Labels: review

#48 Revert "38 feature/like event"
  src/controllers/AuthController.js
  src/server.js
  src/socket/onSocketActions.js
Labels: review

#49 38 feature/like event
  src/server.js
  src/socket/onSocketActions.js
Labels: review

#55 46 feature/get presentation
  src/controllers/SessionController.js
  src/controllers/UserController.js
  src/db/actions.js
  src/models/Presentation.js
  src/socket/onSocketActions.js
  src/socket/socket.js
Labels: review

#57 bugfix for workspaces
  package.json
  src/db/actions.js
Labels: review

#56 Add backend to insert seleced workspace to session
  src/controllers/SessionController.js
Labels: review

#47 Feature/190 feature/pages contact api
  .env.dist
  package-lock.json
  package.json
  src/controllers/MessageController.js
  src/server.js
  yarn.lock
Labels: review

#61 enhancement/mesages update user
  .prettierrc
  .vscode/settings.json
  src/controllers/UserController.js
  src/db/actions.js
Labels: review

#62 Add default avatar on signup
  src/db/actions.js
Labels: review

#65 Pause and set disconnected status when host disconnects from session. Closes #64 #63
  src/socket/onSocketActions.js
  src/socket/socket.js
Labels: bug

#67 Bugfix: Update user info
  src/db/actions.js
  yarn.lock
Labels: review

#70 Fixed url to get secure url
  src/db/actions.js
Labels: review

#74 Integrate custom callback with passport to send status codes. Closes #72
  src/controllers/AuthController.js
  src/services/passport.js
Labels: review
